In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
x = pd.read_csv("dataR2.csv")
x = x.drop(x.columns[0],axis=1)
y = x['Classification']
x = x.drop(x.columns[-1],axis=1)
#print(x)
#print(y)
#print(x.columns)
#print(x)
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size = 0.3,random_state = 1)
#print(train_x.shape)
#print(train_y.shape)
#print(test_x.shape)
#print(test_y.shape)


from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_x,train_y)
pred = model.predict(test_x)
score = accuracy_score(test_y,pred)
print(confusion_matrix(test_y,pred))
print("ACCURACY FOR LOGISTIC REGRESSION = ",score*100)

from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf.fit(train_x,train_y)
pred2 = clf.predict(test_x)
score2 = accuracy_score(test_y,pred2)
print(confusion_matrix(test_y,pred2))
print("ACCURACY FOR DECISION TREE =",score2*100)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(train_x, train_y)
pred3 = classifier.predict(test_x)
print(confusion_matrix(test_y, pred3))
score3= accuracy_score(test_y,pred3) 
print("Accuracy using kNeighbours",score3*100)
                                                                                                                   
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(train_x, train_y)
pred4 = classifier.predict(test_x)
print(confusion_matrix(test_y, pred4))
score4 = accuracy_score(test_y,pred4)
print("Accuracy using SVM-linear",score4*100)

from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(train_x, train_y)
pred4 = classifier.predict(test_x)
print(confusion_matrix(test_y, pred4))
score4 = accuracy_score(test_y,pred4)
print("Accuracy using SVM-kernel",score4*100)

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(train_x, train_y)
pred5 = classifier.predict(test_x)
print(confusion_matrix(test_y, pred5))
score5 = accuracy_score(test_y,pred5)
print("Accuracy using Randomforest",score5*100)
print("\n")


from sklearn.model_selection import GridSearchCV

penalty = ['l1','l2']
C=np.arange(1,10,1)
hyperparameters = dict(C=C, penalty=penalty)

grid_search = GridSearchCV(model,hyperparameters, cv=10, verbose=0,iid=False)
best_model = grid_search.fit(x,y)
#print(best_model,"\n")
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'],"\n")
print('Best C:', best_model.best_estimator_.get_params()['C'],"\n")
print("best logistic regression from grid search: %f" % grid_search.best_estimator_.score(test_x,pred),"\n")

#print(best_model.predict(x))

[[ 9  3]
 [ 4 19]]
ACCURACY FOR LOGISTIC REGRESSION =  80.0
[[ 8  4]
 [ 4 19]]
ACCURACY FOR DECISION TREE = 77.14285714285715
[[ 5  7]
 [10 13]]
Accuracy using kNeighbours 51.42857142857142
[[ 8  4]
 [ 5 18]]
Accuracy using SVM-linear 74.28571428571429
[[ 0 12]
 [ 0 23]]
Accuracy using SVM-kernel 65.71428571428571
[[ 7  5]
 [ 7 16]]
Accuracy using Randomforest 65.71428571428571


Best Penalty: l1 

Best C: 5 

best logistic regression from grid search: 0.914286 

